# Generated by Django 4.2.1 on 2023-05-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_admissionsmodel_studylevelmodel_universitymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitymodel',
            name='admission',
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='admission',
            field=models.ManyToManyField(to='university.admissionsmodel', verbose_name='admission'),
        ),
    ]
