# Generated by Django 4.2.1 on 2023-05-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_admissionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('logo', models.FileField(upload_to='university', verbose_name='logo')),
                ('descriptions', models.TextField(verbose_name='descriptions')),
                ('terms_and_conditions', models.TextField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.admissionsmodel', verbose_name='admission')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.countrymodel', verbose_name='country')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.studylevelmodel', verbose_name='level')),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
            },
        ),
    ]
