# Generated by Django 3.2.19 on 2023-05-19 21:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_remove_universitymodel_admission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fields', ckeditor.fields.RichTextField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel')),
            ],
        ),
    ]
