# Generated by Django 3.2.19 on 2023-05-19 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_universityformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityformmodel',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_uni', to='university.universitymodel'),
        ),
    ]
