# Generated by Django 3.2.19 on 2023-05-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_alter_universityformmodel_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='image',
            field=models.FileField(null=True, upload_to='images/country', verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='UniversityFormModel',
        ),
    ]
