# Generated by Django 3.2.19 on 2023-05-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20230520_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionsmodel',
            name='directions_en',
            field=models.TextField(null=True, verbose_name='directions'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='directions_ru',
            field=models.TextField(null=True, verbose_name='directions'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='directions_uz',
            field=models.TextField(null=True, verbose_name='directions'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='end_date_en',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='end_date_ru',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='end_date_uz',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='start_date_en',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='start_date_ru',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='admissionsmodel',
            name='start_date_uz',
            field=models.DateField(null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='title_en',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='title_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='title_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='studylevelmodel',
            name='level_en',
            field=models.CharField(max_length=90, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='studylevelmodel',
            name='level_ru',
            field=models.CharField(max_length=90, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='studylevelmodel',
            name='level_uz',
            field=models.CharField(max_length=90, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='descriptions_en',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='descriptions_ru',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='descriptions_uz',
            field=models.TextField(null=True, verbose_name='descriptions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='terms_and_conditions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='terms_and_conditions_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='terms_and_conditions_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Terms and Conditions'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='title_en',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='title_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='universitymodel',
            name='title_uz',
            field=models.CharField(max_length=120, null=True, verbose_name='title'),
        ),
    ]
