# Generated by Django 3.2.19 on 2023-05-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20230520_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='end_date_en',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='end_date_ru',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='end_date_uz',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='start_date_en',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='start_date_ru',
        ),
        migrations.RemoveField(
            model_name='admissionsmodel',
            name='start_date_uz',
        ),
    ]
