# Generated by Django 3.2.19 on 2023-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_auto_20230520_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionsmodel',
            name='end_date',
            field=models.DateField(verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='admissionsmodel',
            name='start_date',
            field=models.DateField(verbose_name='start_date'),
        ),
    ]
