# Generated by Django 3.2.19 on 2023-05-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20230520_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_uz', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('image', models.FileField(upload_to='blogs', verbose_name='image')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('short_description_en', models.TextField(null=True, verbose_name='Short description')),
                ('short_description_ru', models.TextField(null=True, verbose_name='Short description')),
                ('short_description_uz', models.TextField(null=True, verbose_name='Short description')),
                ('long_description', models.TextField(verbose_name='Long description')),
                ('long_description_en', models.TextField(null=True, verbose_name='Long description')),
                ('long_description_ru', models.TextField(null=True, verbose_name='Long description')),
                ('long_description_uz', models.TextField(null=True, verbose_name='Long description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
