# Generated by Django 3.2.19 on 2023-05-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_universityinputfieldmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinputfieldmodel',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='universityinputfieldmodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='universityinputfieldmodel',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='universityinputfieldmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
