# Generated by Django 3.2.19 on 2023-05-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_auto_20230529_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universityinputfieldmodel',
            name='user',
        ),
    ]
