# Generated by Django 3.2.19 on 2023-05-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_remove_universityinputfieldmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinputfieldmodel',
            name='input_type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('text', 'Text')], default='text', max_length=20, verbose_name='input type'),
        ),
    ]
