# Generated by Django 3.2.19 on 2023-05-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_universityinputfieldmodel_input_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('year', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=20)),
                ('study_location', models.CharField(blank=True, max_length=100)),
                ('birthday_month', models.CharField(choices=[('', 'Select your birthday month'), ('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('cell_code', models.CharField(choices=[('', 'Cell / Phone number / Country'), ('86', 'China Mainland +86'), ('20', 'Egypt +20'), ('91', 'India +91'), ('234', 'Nigeria +234'), ('92', 'Pakistan +92'), ('7', 'Russia +7')], max_length=10)),
                ('start_studying', models.IntegerField(choices=[('', 'When would you like to start studying?'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027')])),
                ('subject', models.CharField(blank=True, choices=[('', 'Which subject would you like to study? (optional)'), ('L1-Social Sciences', 'Social Sciences and Humanities'), ('L1-Business', 'Business and Management'), ('L1-Finance', 'Accounting, Economics and Finance'), ('L1-Arts', 'Arts'), ('L1-Computing', 'Computing and Information Systems'), ('L1-Engineering', 'Engineering')], max_length=100)),
                ('residence', models.CharField(choices=[('', 'Where do you live?'), ('CN', 'China Mainland'), ('EG', 'Egypt'), ('IN', 'India'), ('NG', 'Nigeria'), ('PK', 'Pakistan')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
