# Generated by Django 3.2.19 on 2023-06-05 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0016_alter_contactmodel_start_studying'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.universitymodel')),
            ],
            options={
                'verbose_name': 'Paymet',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
