# Generated by Django 3.2.19 on 2023-06-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0017_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
