# Generated by Django 3.2.19 on 2023-06-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0018_auto_20230605_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitymodel',
            name='price',
            field=models.IntegerField(max_length=50, null=True, verbose_name='price'),
        ),
    ]
