# Generated by Django 3.2.19 on 2023-06-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0019_universitymodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.CharField(max_length=300, null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=90, null=True, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(max_length=90, null=True, verbose_name='last_name'),
        ),
        migrations.AddField(
            model_name='payment',
            name='male',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='phone'),
        ),
    ]
